apiVersion: v1
kind: Service
metadata:
    name: "bestreadscluster-6e86"
    labels:
        app: "bestreadscluster-6e86"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "bestreadscluster-6e86"